export const copy = {
  app: {
    name: 'OjaPaddi',
    tagline: 'Market Friend',
  },
  home: {
    title: 'Home',
    recordSale: 'Record a Sale',
    addProduct: 'Add Product',
    runningLow: 'Running Low',
    walkInCustomer: 'Walk-in Customer',
  },
  sales: {
    title: 'Sales',
    saleRecorded: 'Sale recorded! 🎉',
  },
  products: {
    title: 'Products',
    productAdded: 'Product added ✓',
  },
  customers: {
    title: 'Customers',
  },
  more: {
    title: 'More',
    upgradeToPro: 'Upgrade to Pro',
    businessProfile: 'Business Profile',
    businessProfileDesc: 'Manage your public business info',
  },
  auth: {
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
  },
  whatsapp: {
    thankYouPatronage: 'Thank you for your patronage!',
    tapToViewOrder: 'Tap to view & order',
    receiptHeader: 'Receipt',
    shareReceipt: 'Share via WhatsApp',
    shareProduct: 'Share Product',
  },
  addProduct: {
    title: 'Add Product',
    imagePlaceholder: 'Tap to add photo',
    save: 'Save Product',
    saving: 'Saving...',
    imageRequired: 'Product image is required',
  },
  productOnboarding: {
    stepIndicator: 'Step {current} of {total}',
    welcome: {
      title: 'Let\'s set up your first product! 🎉',
      subtitle: 'We\'ll guide you through adding your product in just a few simple steps.',
      button: 'Get Started',
    },
    photo: {
      title: 'Add a product photo',
      subtitle: 'Customers love to see what they\'re buying!',
      addPhoto: 'Add Photo',
      skip: 'Skip for now',
    },
    details: {
      title: 'Product details',
      subtitle: 'Tell us about your product',
      namePlaceholder: 'e.g., Ankara Top',
      categoryPlaceholder: 'e.g., Clothing',
      descriptionPlaceholder: 'Describe your product...',
    },
    pricing: {
      title: 'Price & Stock',
      subtitle: 'Set your selling price and quantity',
      priceLabel: 'Selling Price (₦)',
      pricePlaceholder: '0.00',
      quantityLabel: 'Quantity',
      quantityPlaceholder: '0',
    },
    review: {
      title: 'All done! 🎉',
      subtitle: 'Your product is ready to go',
      button: 'Add Product',
      adding: 'Adding...',
      successTitle: 'Product added!',
      successSubtitle: 'Great start to your inventory',
      addAnother: 'Add Another Product',
      viewProducts: 'View Products',
    },
  },
  businessProfile: {
    title: 'Business Profile',
    subtitle: 'Your public store info',
    logoLabel: 'Business Logo',
    logoHint: 'Tap to change logo',
    nameLabel: 'Business Name',
    namePlaceholder: 'Your business name',
    categoryLabel: 'Business Category',
    categoryPlaceholder: 'Choose a category',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Tell customers what you sell...',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '0801 234 5678',
    emailLabel: 'Email Address',
    emailPlaceholder: 'you@business.com',
    addressLabel: 'Street Address',
    addressPlaceholder: '12 Market Road',
    cityLabel: 'City',
    cityPlaceholder: 'Lagos',
    stateLabel: 'State',
    statePlaceholder: 'Lagos',
    whatsappLabel: 'WhatsApp Number',
    whatsappPlaceholder: '2348012345678',
    saveButton: 'Save Changes',
    saving: 'Saving...',
    saved: 'Saved!',
    error: 'Failed to save changes',
    fetchError: 'Failed to load business profile',
  },
} as const;
